/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FileList: typeof import('./src/components/filemanges/FileList.vue')['default']
    FileMange: typeof import('./src/components/filemanges/FileMange.vue')['default']
    FileMangeToolbar: typeof import('./src/components/filemanges/FileMangeToolbar.vue')['default']
    FileTypeList: typeof import('./src/components/filemanges/FileTypeList.vue')['default']
    HomeHeader: typeof import('./src/components/home/HomeHeader.vue')['default']
    HomeSide: typeof import('./src/components/home/HomeSide.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
